### ISSUE TITLE
Parser is missing keys with parameters

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/xgettext-php#4]
I am facing this problem. Those two types of keys seems to be ignored while updating catalog into POedit.

`{{i18n-t "{{count}}% stuff" count=var}}`
`<%= _t("I like {{stuff}}.", { stuff: something }) %>`

**Comment by guillaumepotier** [comment]
Done

**Comment by guillaumepotier** [comment]
Still missing support for that

```js
_t("Send <span class='Instructions-em'>{{event_keyword}}</span> followed by a space and your message to <span class='Instructions-em'>{{event_sms}}</span>.", {
    event_keyword: _.escape(getInfo("wiz.keyword")),
    event_sms: sms_number
  })
```

but meh, fuck it, use an intermediate var for `_.escape(getInfo("wiz.keyword"))` <3
