### ISSUE TITLE
Issue Installing xgettext-php on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by miketeo** [Wisembly/xgettext-php#5]
Hi, I had created the composer.json and tried running "composer install". But the command threw the following error.

> 
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package wisembly/xgettext-php could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Did I miss out anything?

**Comment by guillaumepotier** [comment]
Hi there,

I think I missed to add the project version in composer, this should be a warning, not an error right?

**Comment by miketeo** [comment]
@guillaumepotier : Same problem (not a warning) as the composer command aborts.

**Comment by guillaumepotier** [comment]
Oh, I know. The package name is `xgettext` and not `xgettext-php`.. :)
